name: Build APK (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      app_version_name:
        description: 'App Version Name (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      app_version_code:
        description: 'App Version Code (integer, e.g., 1)'
        required: true
        default: '1'

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bubblewrap CLI
        run: npm install -g @bubbleapps/bubblewrap-cli@latest # Ensure latest

      - name: Set up JDK
        id: setup_jdk # Give an ID to access its outputs if needed
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Debug JDK Installation
        run: |
          echo "JAVA_HOME is: $JAVA_HOME"
          echo "JDK Path from setup-java action: ${{ steps.setup_jdk.outputs.path }}"
          echo "--- Checking for java executable ---"
          ls -l "$JAVA_HOME/bin/java"
          "$JAVA_HOME/bin/java" -version
          echo "--- Checking for javac executable ---"
          ls -l "$JAVA_HOME/bin/javac"
          "$JAVA_HOME/bin/javac" -version
          echo "--- Checking PATH ---"
          echo "$PATH"
          which java
          which javac

      - name: Decode and Restore Keystore
        run: |
          echo "Restoring keystore..."
          echo "${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > android.keystore
          echo "Keystore restored to android.keystore"

      - name: Build APK with Bubblewrap
        id: build_apk
        # JAVA_HOME should be inherited by the shell environment from the setup-java step
        run: |
          APP_VERSION_NAME="${{ github.event.inputs.app_version_name }}"
          APP_VERSION_CODE="${{ github.event.inputs.app_version_code }}"

          echo "Building APK for version ${APP_VERSION_NAME} (code ${APP_VERSION_CODE})"
          echo "Providing 'n' and then '$JAVA_HOME' to Bubblewrap prompts."

          # Use a command group to pipe multiple lines to bubblewrap's stdin
          # 1. Answer "n" to "Do you want Bubblewrap to install the JDK?"
          # 2. Answer "$JAVA_HOME" to "Path to your existing JDK 17:"
          { \
            echo "n"; \
            echo "$JAVA_HOME"; \
          } | bubblewrap build \
            --manifest ./twa-manifest.json \
            --signingKeyPath ./android.keystore \
            --signingKeyAlias "${{ secrets.ANDROID_KEY_ALIAS }}" \
            --signingKeyPassword "${{ secrets.ANDROID_KEY_PASSWORD }}" \
            --keystorePassword "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" \
            --appVersionName "${APP_VERSION_NAME}" \
            --appVersionCode "${APP_VERSION_CODE}" \
            --skipPwaValidation

          APK_PATH="./app-release-signed.apk"
          ARTIFACT_FILENAME="YourAppName-${APP_VERSION_NAME}-code${APP_VERSION_CODE}.apk"
          echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "artifact_filename=${ARTIFACT_FILENAME}" >> $GITHUB_OUTPUT

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk-${{ github.event.inputs.app_version_name }}
          path: ${{ steps.build_apk.outputs.apk_path }}
          if-no-files-found: error