name: Build APK (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      app_version_name:
        description: 'App Version Name (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      app_version_code:
        description: 'App Version Code (integer, e.g., 1)'
        required: true
        default: '1'

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred LTS version

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Set up JDK 17
        id: setup_jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Pre-create Bubblewrap config with JDK path
        run: |
          echo "Manually creating Bubblewrap config directory and file..."
          CONFIG_DIR=~/.bubblewrap
          CONFIG_FILE=$CONFIG_DIR/config.json
          mkdir -p "$CONFIG_DIR"
          echo "{ \"jdkPath\": \"$JAVA_HOME\" }" > "$CONFIG_FILE" # Only jdkPath
          echo "Bubblewrap config.json created with JDK path."
          echo "Contents of ~/.bubblewrap/config.json:"
          cat "$CONFIG_FILE"
          echo "----------------------------------------"

      - name: Decode and Restore Keystore
        run: |
          echo "Restoring keystore..."
          echo "${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > android.keystore
          echo "Keystore restored to android.keystore"

      - name: Build APK with Bubblewrap
        id: build_apk
        run: |
          APP_VERSION_NAME="${{ github.event.inputs.app_version_name }}"
          APP_VERSION_CODE="${{ github.event.inputs.app_version_code }}"

          echo "Building APK for version ${APP_VERSION_NAME} (code ${APP_VERSION_CODE})"
          echo "Piping 'y' then 'y' to bubblewrap build for Android SDK install and license agreement..."

          # 1. First 'y' for "Do you want Bubblewrap to install the Android SDK?"
          # 2. Second 'y' for "Do you agree to the Android SDK terms and conditions?"
          { \
            echo "y"; \
            echo "y"; \
          } | bubblewrap build \
            --manifest ./twa-manifest.json \
            --signingKeyPath ./android.keystore \
            --signingKeyAlias "${{ secrets.ANDROID_KEY_ALIAS }}" \
            --signingKeyPassword "${{ secrets.ANDROID_KEY_PASSWORD }}" \
            --keystorePassword "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" \
            --appVersionName "${APP_VERSION_NAME}" \
            --appVersionCode "${APP_VERSION_CODE}" \
            --skipPwaValidation

          # The Android SDK download and setup will happen here.
          # This might take a few minutes the first time.

          APK_PATH="./app-release-signed.apk"
          ARTIFACT_FILENAME="YourAppName-${APP_VERSION_NAME}-code${APP_VERSION_CODE}.apk"
          echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "artifact_filename=${ARTIFACT_FILENAME}" >> $GITHUBOUTPUT

      - name: Verify Android SDK installation (Optional - for debugging)
        run: |
          echo "Checking for Android SDK installation..."
          ls -la ~/.bubblewrap/ || echo "No ~/.bubblewrap directory"
          ls -la ~/.bubblewrap/android_sdk/ || echo "No ~/.bubblewrap/android_sdk directory"
          echo "Updated contents of ~/.bubblewrap/config.json:"
          cat ~/.bubblewrap/config.json || echo "~/.bubblewrap/config.json not found"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk-${{ github.event.inputs.app_version_name }}
          path: ${{ steps.build_apk.outputs.apk_path }}
          if-no-files-found: error