name: Build APK (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      app_version_name:
        description: 'App Version Name (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      app_version_code:
        description: 'App Version Code (integer, e.g., 1)'
        required: true
        default: '1'

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Set up JDK
        id: setup_jdk # Give an ID to access its outputs if needed
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Debug JDK Installation
        run: |
          echo "Workflow JAVA_HOME is: $JAVA_HOME"
          echo "Path from setup_jdk step: ${{ steps.setup_jdk.outputs.path }}"
          echo "Checking java version from JAVA_HOME:"
          "$JAVA_HOME/bin/java" -version
          echo "Checking javac version from JAVA_HOME:"
          "$JAVA_HOME/bin/javac" -version
          echo "Listing contents of JAVA_HOME/bin:"
          ls -la "$JAVA_HOME/bin"

      - name: Decode and Restore Keystore
        run: |
          echo "Restoring keystore..."
          echo "${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > android.keystore
          echo "Keystore restored to android.keystore"

      - name: Build APK with Bubblewrap
        id: build_apk
        env:
          JAVA_HOME_FROM_SETUP: ${{ steps.setup_jdk.outputs.path }}
        run: |
          APP_VERSION_NAME="${{ github.event.inputs.app_version_name }}"
          APP_VERSION_CODE="${{ github.event.inputs.app_version_code }}"

          echo "Building APK for version ${APP_VERSION_NAME} (code ${APP_VERSION_CODE})"
          echo "Using JDK from setup step: $JAVA_HOME_FROM_SETUP"
          echo "Attempting with --noJdkInstall and --jdkPath flags."
          
          bubblewrap build \
            --manifest ./twa-manifest.json \
            --noJdkInstall \
            --jdkPath "$JAVA_HOME_FROM_SETUP" \
            --signingKeyPath ./android.keystore \
            --signingKeyAlias "${{ secrets.ANDROID_KEY_ALIAS }}" \
            --signingKeyPassword "${{ secrets.ANDROID_KEY_PASSWORD }}" \
            --keystorePassword "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" \
            --appVersionName "${APP_VERSION_NAME}" \
            --appVersionCode "${APP_VERSION_CODE}" \
            --skipPwaValidation

          APK_PATH="./app-release-signed.apk"
          ARTIFACT_FILENAME="YourAppName-${APP_VERSION_NAME}-code${APP_VERSION_CODE}.apk"
          echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "artifact_filename=${ARTIFACT_FILENAME}" >> $GITHUB_OUTPUT

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk-${{ github.event.inputs.app_version_name }}
          path: ${{ steps.build_apk.outputs.apk_path }}
          if-no-files-found: error